apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: docker-devfile-sample-hello-world-shse
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: docker-devfile-sample-hello-world-shse
    app.kubernetes.io/part-of: test-app-eumz
  name: docker-devfile-sample-hello-world-shse
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: docker-devfile-sample-hello-world-shse
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: docker-devfile-sample-hello-world-shse
    spec:
      containers:
      - image: quay.io/quay_xjiang/build-e2e-gjtg-tenant/test-app-eumz/docker-devfile-sample-hello-world-shse@sha256:a527143b88240b04cd5041fd9a66a78c7c3f0f5df421d9571b5a1d2ebe6ab760
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
